name: Publish package
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    - name: Setup git
      run: |
        git config --local user.email "sysadmin@myalbum.com"
        git config --local user.name "MyAlbum System"
    - run: npm version minor
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        tags: false
        github_token: ${{ secrets.GITHUB_TOKEN }}